### ISSUE TITLE
Error in Clean Up

### ISSUE THREAD

**Issue by akshaykrjain** [jealie/install_tmux#1]
Hi Jealie,

Thanks for providing this script.

I was able to install tmux without root access.

However, I faced below error at the end of script-

**rm: cannot remove `/home/jainaks/tmux_tmp/install_tmux': Directory not empty**

**Comment by jealie** [comment]
Thanks for the report.

I can not reproduce the bug: I believe your `rm` command does not accept the -`rf` (recursive, do not ask) flag used to clean up the directory that was created. Maybe you aliased `rm` to something else? Like `safe-rm`?

In any case, try running manually `rm -rf $HOME/tmux_tmp` to see if that helps, or delete manually in some other way that directory.
